FROM openjdk:8-jdk-alpine

COPY target/global-management-service-spring-boot-0.0.1-SNAPSHOT.jar global-management-service-spring-boot-0.0.1-SNAPSHOT.jar
CMD ['java', '-jar', 'lglobal-management-service-spring-boot-0.0.1-SNAPSHOT.jar']
